### ISSUE TITLE
/Clock publish rate too low. 

### ISSUE THREAD

**Issue by rahulranjan29** [code-iai/ROSIntegration#198]
Hi,

Issue: I'm using the ROSIntegration plugin with 'simulated time = true'. When I check the topic publication rate in ROS via  ```rostopic hz /clock```, I only get 3Hz.  To check if this is caused on the Unreal Side, I calculated the rate at which ```UROSIntegrationGameInstance::OnWorldTickStart(UWorld * World, ELevelTick TickType, float DeltaTime)``` is called and it's ~30Hz.  It looks like messages are being lost over TCP. I'm not sure what is happening.
```
clock: 
  secs: 1693475858
  nsecs: 126977761
---
clock: 
  secs: 1693475858
  nsecs: 460311265
---
clock: 
  secs: 1693475858
  nsecs: 793644673
---
clock: 
  secs: 1693475859
  nsecs: 126978177
---
clock: 
  secs: 1693475859
  nsecs: 460311681
---
clock: 
  secs: 1693475859
  nsecs: 793645089
---
clock: 
  secs: 1693475860
  nsecs: 126978593
---
clock: 
  secs: 1693475860
  nsecs: 460312001
---
clock: 
  secs: 1693475860
  nsecs: 794506977
---
clock: 
  secs: 1693475861
  nsecs: 128380193
```

How can I debug this? Is there a way to increase the clock publication frequency without setting the bfixedUpdateInterval variable?

My Setup:
Vanilla Unreal Engine 5.2 project with ROSIntegration plugin (dev branch)
ROS Noetic on WSL2 with Ubuntu 20.04
 * /rosdistro: noetic
 * /rosversion: 1.16.0
